[2023-07-22 00:24:36,257] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22 00:24:36,374] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22 00:24:36,377] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-22 00:24:36,380] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-22 00:24:36,383] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-22 00:24:36,500] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_datos> on 2023-07-21 00:00:00+00:00
[2023-07-22 00:24:36,532] {standard_task_runner.py:52} INFO - Started process 15912 to run task
[2023-07-22 00:24:36,568] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'transformar_datos', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpxvuhyi_0', '--error-file', '/tmp/tmpngzlhe6q']
[2023-07-22 00:24:36,576] {standard_task_runner.py:80} INFO - Job 78: Subtask transformar_datos
[2023-07-22 00:24:37,100] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.transformar_datos scheduled__2023-07-21T00:00:00+00:00 [running]> on host bd4a51b00e09
[2023-07-23 14:52:37,623] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=transformar_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-21T00:00:00+00:00
[2023-07-23 14:52:41,162] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-07-23 14:52:41,609] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 15912. PIDs of all processes in the group: [15912]
[2023-07-23 14:52:41,611] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 15912
[2023-07-23 14:52:41,623] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-23 14:52:42,535] {process_utils.py:75} INFO - Process psutil.Process(pid=15912, status='terminated', exitcode=0, started='2023-07-22 00:24:36') (15912) terminated with exit code 0
