[2023-07-16 18:12:10,450] {taskinstance.py:1173} INFO - Dependencies not met for <TaskInstance: dag_con_conexion_postgres.transformar_datos scheduled__2023-07-15T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-07-16 18:12:10,559] {local_task_job.py:101} INFO - Task is not able to be run
